const actionType = {
  NEW_GAME: 'NEW_GAME',
  NEXT_ROUND: 'NEXT_ROUND',
  TOGGLE_PLAYER: 'TOGGLE_PLAYER',
  GAME_OVER: 'GAME_OVER',
  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
} as const

export const {
  NEW_GAME,
  NEXT_ROUND,
  TOGGLE_PLAYER,
  GAME_OVER,
  UPDATE_MESSAGE,
} = actionType
